// <auto-generated />
using System;
using Database.Test.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Database.Test.Migrations
{
    [DbContext(typeof(TestDbContext))]
    [Migration("20190829150926_test")]
    partial class test
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("Database.Test.Models.TestEfObject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CoolString");

                    b.HasKey("Id");

                    b.ToTable("testEfObjects");
                });
#pragma warning restore 612, 618
        }
    }
}
