version: "3"
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    expose:
      - "27017"
  # mongo-seed:
  #   build: ./mongo-seed
  #   links:
  #     - mongo
  #   restart: on-failure
